# Create datasets with duplicates

In [3]:
import pandas as pd

cardata = {"Mercedes": [2, 4, 0, 4, 0, 3],
           "Ford": [3, 0 , 13, 1, 6, 12],
           "Tata": [9, 3, 4, 1, 0, 0],
           "Renault": [12, 1, 0, 0, 3, 1],
          }
carsales = pd.DataFrame(cardata)
carsales.index.rename("Sales place", inplace=True)
carsales.rename(index={0: "One",
                       1: "Two",
                       2: "Three",
                       3: "Four",
                       4: "Five",
                       5: "Six",
                      },
                inplace = True)

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0    13     4        0
Four                4     1     1        0
Five                0     6     0        3
Six                 3    12     0        1

In [4]:
places = ["Europe 1", "Australia 1", "USA 1", "Asia 1", "Africa 1", "South America 1"]
carsales.insert(0, "SalesPlaceName", places, allow_duplicates=True)

carsales

              SalesPlaceName  Mercedes  Ford  Tata  Renault
Sales place
One                 Europe 1         2     3     9       12
Two              Australia 1         4     0     3        1
Three                  USA 1         0    13     4        0
Four                  Asia 1         4     1     1        0
Five                Africa 1         0     6     0        3
Six          South America 1         3    12     0        1

In [5]:
nsp1 = {"SalesPlaceName": "South America 1",
        "Mercedes": 3,
        "Ford": 2,
        "Tata":1,
        "Renault": 1,
       }
newSalesPlace1 = pd.DataFrame(nsp1, index=["Seven"])
newSalesPlace1

        SalesPlaceName  Mercedes  Ford  Tata  Renault
Seven  South America 1         3     2     1        1

In [6]:
nsp2 = {"SalesPlaceName": "Asia 1",
        "Mercedes": 4,
        "Ford": 1,
        "Tata": 1,
        "Renault": 0,
       }
newSalesPlace2 = pd.DataFrame(nsp2, index=["Eight"])
newSalesPlace2

      SalesPlaceName  Mercedes  Ford  Tata  Renault
Eight         Asia 1         4     1     1        0

## Final dataset with duplicates

There are two different duplicates:
1. One **key-based** duplicate - *South America 1* (only the sales place name)
2. One complete **data** duplicate - *Asia 1* (all values)

In [7]:
carsales = pd.concat([carsales, newSalesPlace1, newSalesPlace2])
carsales

        SalesPlaceName  Mercedes  Ford  Tata  Renault
One           Europe 1         2     3     9       12
Two        Australia 1         4     0     3        1
Three            USA 1         0    13     4        0
Four            Asia 1         4     1     1        0
Five          Africa 1         0     6     0        3
Six    South America 1         3    12     0        1
Seven  South America 1         3     2     1        1
Eight           Asia 1         4     1     1        0

# Pandas' `.duplicated()` function

can find **key-based** duplicates in a DataFrame by limiting the duplicates to the key column(s)<br>
`keep=first/last` may determine which duplicates to keep in the DataFrame or an attached DataFrame<br>
`keep=False` marks all duplicates.

In [8]:
carsales.duplicated(subset=["SalesPlaceName"])

One      False
Two      False
Three    False
Four     False
Five     False
Six      False
Seven     True
Eight     True
dtype: bool

In [11]:
carsales.duplicated(subset=["SalesPlaceName"], keep="last")

One      False
Two      False
Three    False
Four      True
Five     False
Six       True
Seven    False
Eight    False
dtype: bool

In [13]:
carsales.duplicated(subset=["SalesPlaceName"], keep=False)

One      False
Two      False
Three    False
Four      True
Five     False
Six       True
Seven     True
Eight     True
dtype: bool

## Complete duplicates

In [14]:
carsales.duplicated()

One      False
Two      False
Three    False
Four     False
Five     False
Six      False
Seven    False
Eight     True
dtype: bool

# Pandas' `.drop_duplicates()` function

In [15]:
carsalesDupRem = carsales.drop_duplicates(subset=["SalesPlaceName"], keep="first")
carsalesDupRem

        SalesPlaceName  Mercedes  Ford  Tata  Renault
One           Europe 1         2     3     9       12
Two        Australia 1         4     0     3        1
Three            USA 1         0    13     4        0
Four            Asia 1         4     1     1        0
Five          Africa 1         0     6     0        3
Six    South America 1         3    12     0        1

## More `subset` columns

useful in a multi-index environment

In [21]:
carsalesDupRem2 = carsales.drop_duplicates(subset=["SalesPlaceName", "Mercedes"], keep="last")
carsalesDupRem2

        SalesPlaceName  Mercedes  Ford  Tata  Renault
One           Europe 1         2     3     9       12
Two        Australia 1         4     0     3        1
Three            USA 1         0    13     4        0
Five          Africa 1         0     6     0        3
Seven  South America 1         3     2     1        1
Eight           Asia 1         4     1     1        0

In [22]:
carsalesDupRem3 = carsales.drop_duplicates(subset=["SalesPlaceName", "Ford"], keep="last")
carsalesDupRem3

        SalesPlaceName  Mercedes  Ford  Tata  Renault
One           Europe 1         2     3     9       12
Two        Australia 1         4     0     3        1
Three            USA 1         0    13     4        0
Five          Africa 1         0     6     0        3
Six    South America 1         3    12     0        1
Seven  South America 1         3     2     1        1
Eight           Asia 1         4     1     1        0