In [1]:
import pandas as pd

cardata = {"Mercedes": [2, 4, 0, 4, 0, 3],
           "Ford": [3, 0, 0, 1, 6, 12],
           "Tata": [9, 3, 4, 1, 0, 0],
           "Renault": [12, 1, 0, 0, 3, 1],
          }
carsales = pd.DataFrame(cardata)
carsales.index.rename("Sales place", inplace=True)
carsales.rename(index={0: "One",
                       1: "Two",
                       2: "Three",
                       3: "Four",
                       4: "Five",
                       5: "Six",
                      },
                inplace=True)
carsales

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Five                0     6     0        3
Six                 3    12     0        1

# `.sort_values()`

**Note!** we do not use `inplace=True`

- sort on one column

In [2]:
carsales.sort_values(by=["Ford"])

             Mercedes  Ford  Tata  Renault
Sales place
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
One                 2     3     9       12
Five                0     6     0        3
Six                 3    12     0        1

In [3]:
carsales.sort_values(by=["Ford"], ascending=False)

             Mercedes  Ford  Tata  Renault
Sales place
Six                 3    12     0        1
Five                0     6     0        3
One                 2     3     9       12
Four                4     1     1        0
Two                 4     0     3        1
Three               0     0     4        0

- Sort on several columns and also hierarchical structures by increasing the number of `by=` columns.<br>
For this non-hierarchical dataset, such a sort has little meaning.

In [4]:
carsales.sort_values(by=["Ford", "Tata"], ascending=False)

             Mercedes  Ford  Tata  Renault
Sales place
Six                 3    12     0        1
Five                0     6     0        3
One                 2     3     9       12
Four                4     1     1        0
Three               0     0     4        0
Two                 4     0     3        1

# `.sort_index()`

- data gets sorted alphabetically

In [6]:
carsales.sort_index()

             Mercedes  Ford  Tata  Renault
Sales place
Five                0     6     0        3
Four                4     1     1        0
One                 2     3     9       12
Six                 3    12     0        1
Three               0     0     4        0
Two                 4     0     3        1

# `.idxmax()`

- find the rows with the largest values for each column

In [7]:
carsales.idxmax()

Mercedes    Two
Ford        Six
Tata        One
Renault     One
dtype: object

- find the columns with the largest value for each row

In [8]:
carsales.idxmax(axis="columns")

Sales place
One       Renault
Two      Mercedes
Three        Tata
Four     Mercedes
Five         Ford
Six          Ford
dtype: object

# `.idxmin()`

- find the rows with the smallest values for each column

In [9]:
carsales.idxmin()

Mercedes    Three
Ford          Two
Tata         Five
Renault     Three
dtype: object

- find the columns with the smallest values for each row

In [10]:
carsales.idxmin(axis="columns")

Sales place
One      Mercedes
Two          Ford
Three    Mercedes
Four      Renault
Five     Mercedes
Six          Tata
dtype: object

# Dealing with duplicated max and min values

- Find the 3 rows with largest Mercedes sales, keep all duplicates

In [11]:
carsales.nlargest(3, "Mercedes", keep="all")

             Mercedes  Ford  Tata  Renault
Sales place
Two                 4     0     3        1
Four                4     1     1        0
Six                 3    12     0        1

- Find the 3 lowest Renault sales, keep all duplicates

In [16]:
carsales.nsmallest(3, "Mercedes", keep="all")

             Mercedes  Ford  Tata  Renault
Sales place
Three               0     0     4        0
Five                0     6     0        3
One                 2     3     9       12

# `.rank()`

- rank the salesplaces per single column (which salesplace sells the most of the Mercedes brand)

In [14]:
carsales["Mercedes"].rank(ascending=False)

Sales place
One      4.0
Two      1.5
Three    5.5
Four     1.5
Five     5.5
Six      3.0
Name: Mercedes, dtype: float64

- rank the salesplaces per column (which salesplace sales the most of a brand)

In [15]:
carsales.rank(ascending=False)

             Mercedes  Ford  Tata  Renault
Sales place
One               4.0   3.0   1.0      1.0
Two               1.5   5.5   3.0      3.5
Three             5.5   5.5   2.0      5.5
Four              1.5   4.0   4.0      5.5
Five              5.5   2.0   5.5      2.0
Six               3.0   1.0   5.5      3.5

- rank the columns per salesplace (which brand sells the most cars for a salesplace)

In [17]:
carsales.rank(axis=1, ascending=False)

             Mercedes  Ford  Tata  Renault
Sales place
One               4.0   3.0   2.0      1.0
Two               1.0   4.0   2.0      3.0
Three             3.0   3.0   1.0      3.0
Four              1.0   2.5   2.5      4.0
Five              3.5   1.0   3.5      2.0
Six               2.0   1.0   4.0      3.0