**Indicator features** or so-called **dummy variables** have many uses.<br> 
They are effectively about transforming a *binned* or *categorical* **feature** or **variable** into a new set of features that indicate if a **state or value** of the original feature is **True** or **False**, one or zero for every row or data point.<br>
The main use of indicator features or dummy variables is in modelling and an indicator feature is considered to make you able to **quantify the impact** which an indicated state or feature has on a modelled phenomenon.

In [2]:
import pandas as pd

- import the `statsmodels` library to showcase the indicator features

In [3]:
import statsmodels.formula.api as sm

In [4]:
medCost = pd.read_csv("insurance_data.csv")
medCost

      Unnamed: 0  age     sex     bmi  children smoker     region      charges
0              0   19  female  27.900         0    yes  southwest  16884.92400
1              1   18    male  33.770         1     no  southeast   1725.55230
2              2   28    male  33.000         3     no  southeast   4449.46200
3              3   33    male  22.705         0     no  northwest  21984.47061
4              4   32    male  28.880         0     no  northwest   3866.85520
...          ...  ...     ...     ...       ...    ...        ...          ...
1333        1333   50    male  30.970         3     no  northwest  10600.54830
1334        1334   18  female  31.920         0     no  northeast   2205.98080
1335        1335   18  female  36.850         0     no  southeast   1629.83350
1336        1336   21  female  25.800         0     no  southwest   2007.94500
1337        1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 8 columns]

# Pandas' `get_dummies()`

## Create a DF with a *region* feature

In [5]:
medCost2 = pd.get_dummies(medCost, columns=["region"], dtype=bool)
medCost2

,Unnamed: 0,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,0,19,female,27.900,0,yes,16884.92400,False,False,False,True
1,1,18,male,33.770,1,no,1725.55230,False,False,True,False
2,2,28,male,33.000,3,no,4449.46200,False,False,True,False
3,3,33,male,22.705,0,no,21984.47061,False,True,False,False
4,4,32,male,28.880,0,no,3866.85520,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1333,1333,50,male,30.970,3,no,10600.54830,False,True,False,False
1334,1334,18,female,31.920,0,no,2205.98080,True,False,False,False
1335,1335,18,female,36.850,0,no,1629.83350,False,False,True,False
1336,1336,21,female,25.800,0,no,2007.94500,False,False,False,True
1337,1337,61,female,29.070,0,yes,29141.36030,False,True,False,False

- For modeling purposes, it is more useful to use **integers instead of booleans** for indicator features.

In [7]:
medCost3 = pd.get_dummies(medCost, columns=["region"], dtype=int)
medCost3

,Unnamed: 0,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,0,19,female,27.900,0,yes,16884.92400,0,0,0,1
1,1,18,male,33.770,1,no,1725.55230,0,0,1,0
2,2,28,male,33.000,3,no,4449.46200,0,0,1,0
3,3,33,male,22.705,0,no,21984.47061,0,1,0,0
4,4,32,male,28.880,0,no,3866.85520,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1333,1333,50,male,30.970,3,no,10600.54830,0,1,0,0
1334,1334,18,female,31.920,0,no,2205.98080,1,0,0,0
1335,1335,18,female,36.850,0,no,1629.83350,0,0,1,0
1336,1336,21,female,25.800,0,no,2007.94500,0,0,0,1
1337,1337,61,female,29.070,0,yes,29141.36030,0,1,0,0

**ones** and **zeros** are useful with standard models because a parameter or set of weights can be multiplied with the indicator feature. <br>
Consequently, <br> $0 *  value = 0$ <br> $1 * value = value$<br>
Functions may simply sum these indicator feature values to create statistics for indicator features, or to separate indicator features in the dataset.