In [7]:
import pandas as pd

cardata = {"Mercedes": [2, 4, 0, 4, 0, 3],
           "Ford": [3, 0, 0, 1, 6, 12],
           "Tata": [9, 3, 4, 1, 0, 0],
           "Renault": [12, 1, 0, 0, 3, 1],
          }
carsales = pd.DataFrame(cardata)
carsales.index.rename("Sales place", inplace=True)
carsales.rename(index={0: "One",
                       1: "Two",
                       2: "Three",
                       3: "Four",
                       4: "Fiverr",
                       5: "Six",
                      },
                inplace=True)
carsales

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Fiverr              0     6     0        3
Six                 3    12     0        1

# Print column names and index labels

In [8]:
carsales.columns

Index(['Mercedes', 'Ford', 'Tata', 'Renault'], dtype='object')

In [9]:
carsales.index

Index(['One', 'Two', 'Three', 'Four', 'Fiverr', 'Six'], dtype='object', name='Sales place')

# Rename columns

## Using a `.rename()` with a dictionary

In [10]:
carsales.rename(columns={"Tata": "Tatra"}, inplace=True)
carsales

             Mercedes  Ford  Tatra  Renault
Sales place
One                 2     3      9       12
Two                 4     0      3        1
Three               0     0      4        0
Four                4     1      1        0
Fiverr              0     6      0        3
Six                 3    12      0        1

## Using `.columns.str.replace()`

In [11]:
carsales.columns = carsales.columns.str.replace("Tatra", "Tatrra")
carsales

             Mercedes  Ford  Tatrra  Renault
Sales place
One                 2     3       9       12
Two                 4     0       3        1
Three               0     0       4        0
Four                4     1       1        0
Fiverr              0     6       0        3
Six                 3    12       0        1

## Replace the entire set of column strings

In [12]:
carsales.columns = ["Mercedes", "Ford", "Tata", "Renault"]
carsales

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Fiverr              0     6     0        3
Six                 3    12     0        1

# Edit index labels

## Using a `.rename()` with a dictionary

In [14]:
carsales.rename(index={"Fiverr": "Five"}, inplace=True)
carsales

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Five                0     6     0        3
Six                 3    12     0        1

## Using  `.index.str.replace()`

In [15]:
carsales.index = carsales.index.str.replace("Five", "Fiverr")
carsales

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Fiverr              0     6     0        3
Six                 3    12     0        1

## Replace the entire index set

This also removes the *index name* set up after DF creation

In [16]:
carsales.index = [0, 1, 2, 3, 4, 5]
carsales

   Mercedes  Ford  Tata  Renault
0         2     3     9       12
1         4     0     3        1
2         0     0     4        0
3         4     1     1        0
4         0     6     0        3
5         3    12     0        1

In [17]:
carsales.index.rename("Sales place", inplace=True)
carsales

             Mercedes  Ford  Tata  Renault
Sales place
0                   2     3     9       12
1                   4     0     3        1
2                   0     0     4        0
3                   4     1     1        0
4                   0     6     0        3
5                   3    12     0        1